In [5]:
import pandas as pd

df = pd.read_csv("student_performance.csv")

df

   Student_ID    Name  Gender  Age  Marks  Attendance Department Result
0         101    Amit    Male   20   85.0          90         IT   Pass
1         102    Riya  Female   21   92.0          95         IT   Pass
2         103   Rahul    Male   20   76.0          78         CS   Pass
3         104   Sneha  Female   22   88.0          88         CS   Pass
4         105   Vikas    Male   21    NaN          70         IT   Fail
5         106   Priya  Female   20   95.0          96         CS   Pass
6         107  Anjali  Female   22   67.0          65         IT   Fail
7         108   Rohan    Male   21   81.0          82         CS   Pass

In [6]:
type(df)

pandas.DataFrame

In [7]:
df.head(3)

   Student_ID   Name  Gender  Age  Marks  Attendance Department Result
0         101   Amit    Male   20   85.0          90         IT   Pass
1         102   Riya  Female   21   92.0          95         IT   Pass
2         103  Rahul    Male   20   76.0          78         CS   Pass

In [8]:
df.tail()

   Student_ID    Name  Gender  Age  Marks  Attendance Department Result
3         104   Sneha  Female   22   88.0          88         CS   Pass
4         105   Vikas    Male   21    NaN          70         IT   Fail
5         106   Priya  Female   20   95.0          96         CS   Pass
6         107  Anjali  Female   22   67.0          65         IT   Fail
7         108   Rohan    Male   21   81.0          82         CS   Pass

In [10]:
df.shape

(8, 8)

In [11]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Age', 'Marks', 'Attendance',
       'Department', 'Result'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  8 non-null      int64
 1   Name        8 non-null      str
 2   Gender      8 non-null      str
 3   Age         8 non-null      int64
 4   Marks       7 non-null      float64
 5   Attendance  8 non-null      int64
 6   Department  8 non-null      str
 7   Result      8 non-null      str
dtypes: float64(1), int64(3), str(4)
memory usage: 644.0 bytes

In [13]:
df.describe()

       Student_ID        Age      Marks  Attendance
count     8.00000   8.000000   7.000000    8.000000
mean    104.50000  20.875000  83.428571   83.000000
std       2.44949   0.834523   9.675694   11.376668
min     101.00000  20.000000  67.000000   65.000000
25%     102.75000  20.000000  78.500000   76.000000
50%     104.50000  21.000000  85.000000   85.000000
75%     106.25000  21.250000  90.000000   91.250000
max     108.00000  22.000000  95.000000   96.000000

In [14]:
marks = df["Marks"]

print(marks)
print(type(marks))

0    85.0
1    92.0
2    76.0
3    88.0
4     NaN
5    95.0
6    67.0
7    81.0
Name: Marks, dtype: float64
<class 'pandas.Series'>

In [18]:
df.loc[0]

Student_ID     101
Name          Amit
Gender        Male
Age             20
Marks         85.0
Attendance      90
Department      IT
Result        Pass
Name: 0, dtype: object

In [16]:
df.loc[0:3]

   Student_ID   Name  Gender  Age  Marks  Attendance Department Result
0         101   Amit    Male   20   85.0          90         IT   Pass
1         102   Riya  Female   21   92.0          95         IT   Pass
2         103  Rahul    Male   20   76.0          78         CS   Pass
3         104  Sneha  Female   22   88.0          88         CS   Pass

In [19]:
df.loc[0:3, ["Name", "Marks", "Result"]]

    Name  Marks Result
0   Amit   85.0   Pass
1   Riya   92.0   Pass
2  Rahul   76.0   Pass
3  Sneha   88.0   Pass

In [20]:
df.iloc[0]

Student_ID     101
Name          Amit
Gender        Male
Age             20
Marks         85.0
Attendance      90
Department      IT
Result        Pass
Name: 0, dtype: object

In [21]:
df.iloc[0:3]

   Student_ID   Name  Gender  Age  Marks  Attendance Department Result
0         101   Amit    Male   20   85.0          90         IT   Pass
1         102   Riya  Female   21   92.0          95         IT   Pass
2         103  Rahul    Male   20   76.0          78         CS   Pass

In [22]:
df.iloc[0:3, 1:4]

    Name  Gender  Age
0   Amit    Male   20
1   Riya  Female   21
2  Rahul    Male   20

In [23]:
df.groupby("Department").agg(
    total_marks=("Marks", "sum"),
    avg_marks=("Marks", "mean"),
    student_count=("Student_ID", "count")
)

            total_marks  avg_marks  student_count
Department
CS                340.0  85.000000              4
IT                244.0  81.333333              4

In [24]:
pd.pivot_table(
    df,
    values="Marks",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

Gender      Female  Male
Department
CS            91.5  78.5
IT            79.5  85.0

In [25]:
df.isnull().sum()

Student_ID    0
Name          0
Gender        0
Age           0
Marks         1
Attendance    0
Department    0
Result        0
dtype: int64

In [26]:
df_fill = df.copy()

df_fill["Marks"] = df_fill["Marks"].fillna(df_fill["Marks"].mean())

df_fill

   Student_ID    Name  Gender  Age      Marks  Attendance Department Result
0         101    Amit    Male   20  85.000000          90         IT   Pass
1         102    Riya  Female   21  92.000000          95         IT   Pass
2         103   Rahul    Male   20  76.000000          78         CS   Pass
3         104   Sneha  Female   22  88.000000          88         CS   Pass
4         105   Vikas    Male   21  83.428571          70         IT   Fail
5         106   Priya  Female   20  95.000000          96         CS   Pass
6         107  Anjali  Female   22  67.000000          65         IT   Fail
7         108   Rohan    Male   21  81.000000          82         CS   Pass

In [27]:
def performance(marks):
    if marks >= 85:
        return "Excellent"
    elif marks >= 70:
        return "Good"
    else:
        return "Needs Improvement"

df_fill["Performance"] = df_fill["Marks"].apply(performance)

df_fill

,Student_ID,Name,Gender,Age,Marks,Attendance,Department,Result,Performance
0,101,Amit,Male,20,85.000000,90,IT,Pass,Excellent
1,102,Riya,Female,21,92.000000,95,IT,Pass,Excellent
2,103,Rahul,Male,20,76.000000,78,CS,Pass,Good
3,104,Sneha,Female,22,88.000000,88,CS,Pass,Excellent
4,105,Vikas,Male,21,83.428571,70,IT,Fail,Good
5,106,Priya,Female,20,95.000000,96,CS,Pass,Excellent
6,107,Anjali,Female,22,67.000000,65,IT,Fail,Needs Improvement
7,108,Rohan,Male,21,81.000000,82,CS,Pass,Good

In [28]:
df_fill["Result_Code"] = df_fill["Result"].map({
    "Pass": 1,
    "Fail": 0
})

df_fill

,Student_ID,Name,Gender,Age,Marks,Attendance,Department,Result,Performance,Result_Code
0,101,Amit,Male,20,85.000000,90,IT,Pass,Excellent,1
1,102,Riya,Female,21,92.000000,95,IT,Pass,Excellent,1
2,103,Rahul,Male,20,76.000000,78,CS,Pass,Good,1
3,104,Sneha,Female,22,88.000000,88,CS,Pass,Excellent,1
4,105,Vikas,Male,21,83.428571,70,IT,Fail,Good,0
5,106,Priya,Female,20,95.000000,96,CS,Pass,Excellent,1
6,107,Anjali,Female,22,67.000000,65,IT,Fail,Needs Improvement,0
7,108,Rohan,Male,21,81.000000,82,CS,Pass,Good,1

In [29]:
df_fill["Age"] = df_fill["Age"].astype(float)

df_fill.dtypes

Student_ID       int64
Name               str
Gender             str
Age            float64
Marks          float64
Attendance       int64
Department         str
Result             str
Performance        str
Result_Code      int64
dtype: object

In [30]:
df_fill = df_fill.rename(
    columns={"Marks": "Total_Marks"}
)

df_fill.head()

,Student_ID,Name,Gender,Age,Total_Marks,Attendance,Department,Result,Performance,Result_Code
0,101,Amit,Male,20.0,85.000000,90,IT,Pass,Excellent,1
1,102,Riya,Female,21.0,92.000000,95,IT,Pass,Excellent,1
2,103,Rahul,Male,20.0,76.000000,78,CS,Pass,Good,1
3,104,Sneha,Female,22.0,88.000000,88,CS,Pass,Excellent,1
4,105,Vikas,Male,21.0,83.428571,70,IT,Fail,Good,0

In [31]:
df_fill.sort_values(
    by="Total_Marks",
    ascending=False
)

,Student_ID,Name,Gender,Age,Total_Marks,Attendance,Department,Result,Performance,Result_Code
5,106,Priya,Female,20.0,95.000000,96,CS,Pass,Excellent,1
1,102,Riya,Female,21.0,92.000000,95,IT,Pass,Excellent,1
3,104,Sneha,Female,22.0,88.000000,88,CS,Pass,Excellent,1
0,101,Amit,Male,20.0,85.000000,90,IT,Pass,Excellent,1
4,105,Vikas,Male,21.0,83.428571,70,IT,Fail,Good,0
7,108,Rohan,Male,21.0,81.000000,82,CS,Pass,Good,1
2,103,Rahul,Male,20.0,76.000000,78,CS,Pass,Good,1
6,107,Anjali,Female,22.0,67.000000,65,IT,Fail,Needs Improvement,0

In [32]:
part1 = df.iloc[:4]
part2 = df.iloc[4:]

combined_df = pd.concat(
    [part1, part2],
    ignore_index=True
)

combined_df

   Student_ID    Name  Gender  Age  Marks  Attendance Department Result
0         101    Amit    Male   20   85.0          90         IT   Pass
1         102    Riya  Female   21   92.0          95         IT   Pass
2         103   Rahul    Male   20   76.0          78         CS   Pass
3         104   Sneha  Female   22   88.0          88         CS   Pass
4         105   Vikas    Male   21    NaN          70         IT   Fail
5         106   Priya  Female   20   95.0          96         CS   Pass
6         107  Anjali  Female   22   67.0          65         IT   Fail
7         108   Rohan    Male   21   81.0          82         CS   Pass

In [35]:
# Create another DataFrame for merging/joining

student_extra = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "City": ["Pune", "Mumbai", "Nashik", "Pune",
             "Mumbai", "Pune", "Nashik", "Mumbai"],
    "Course": ["B.Tech", "B.Tech", "B.Tech", "B.Tech",
               "B.Tech", "B.Tech", "B.Tech", "B.Tech"]
})

student_extra

   Student_ID    City  Course
0         101    Pune  B.Tech
1         102  Mumbai  B.Tech
2         103  Nashik  B.Tech
3         104    Pune  B.Tech
4         105  Mumbai  B.Tech
5         106    Pune  B.Tech
6         107  Nashik  B.Tech
7         108  Mumbai  B.Tech

In [36]:
df1 = df.set_index("Student_ID")
df2 = student_extra.set_index("Student_ID")

joined_df = df1.join(df2[["City", "Course"]])

joined_df

,Name,Gender,Age,Marks,Attendance,Department,Result,City,Course
Student_ID,,,,,,,,,
101,Amit,Male,20,85.0,90,IT,Pass,Pune,B.Tech
102,Riya,Female,21,92.0,95,IT,Pass,Mumbai,B.Tech
103,Rahul,Male,20,76.0,78,CS,Pass,Nashik,B.Tech
104,Sneha,Female,22,88.0,88,CS,Pass,Pune,B.Tech
105,Vikas,Male,21,NaN,70,IT,Fail,Mumbai,B.Tech
106,Priya,Female,20,95.0,96,CS,Pass,Pune,B.Tech
107,Anjali,Female,22,67.0,65,IT,Fail,Nashik,B.Tech
108,Rohan,Male,21,81.0,82,CS,Pass,Mumbai,B.Tech